"""empty message

Revision ID: 59ea8bce4831
Revises: 
Create Date: 2023-09-19 20:19:19.986533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ea8bce4831'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_site',
    sa.Column('id', sa.VARCHAR(length=26), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password', sa.VARCHAR(length=512), nullable=False),
    sa.Column('disabled', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_site')
    # ### end Alembic commands ###
