"""empty message

Revision ID: d5363ad5d362
Revises: dc4fc3c0ca28
Create Date: 2023-09-19 10:53:24.671358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5363ad5d362'
down_revision: Union[str, None] = 'dc4fc3c0ca28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_site', sa.Column('disabled', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_site', 'disabled')
    # ### end Alembic commands ###
