"""empty message

Revision ID: dc4fc3c0ca28
Revises: c783743c0481
Create Date: 2023-09-19 10:08:59.250827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4fc3c0ca28'
down_revision: Union[str, None] = 'c783743c0481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_site', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=26),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_site', 'id',
               existing_type=sa.VARCHAR(length=26),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
