"""empty message

Revision ID: e90587a5a3b2
Revises: d5363ad5d362
Create Date: 2023-09-19 11:09:18.596994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90587a5a3b2'
down_revision: Union[str, None] = 'd5363ad5d362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_site', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user_site', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_site', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user_site', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
